site:
  name: HebergTonServ
  site: 'https://HebergTonServ.vercel.app'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false # orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: HebergTonServ
    template: '%s — HebergTonServ'
  description:
    fr: "🚀 HebergTonServ est le choix privilégié pour l'hébergement de jeux en ligne. Nous proposons des serveurs performants, une latence minimale et une assistance experte pour garantir une expérience de jeu ininterrompue et fluide. Que vous souhaitiez héberger un serveur Minecraft, Fivem ou tout autre jeu populaire, faites confiance à HebergTonServ pour une expérience de jeu optimale."
    en: "🚀 HebergTonServ is the preferred choice for online game hosting. We offer high-performance servers, minimal latency, and expert support to ensure an uninterrupted and smooth gaming experience. Whether you want to host a Minecraft server, Fivem, or any other popular game, trust HebergTonServ for an optimal gaming experience."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: HebergTonServ
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  languages: ['fr', 'en']
  defaultLanguage: 'fr'
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'games' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'dark:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"